
WORDLIST = "wordlist.txt"

puts "// THIS FILE IS GENERATED BY generate_wordlist.rb. DO NOT MODIFY IT!"
puts "#ifndef WORDLIST_H"
puts "#define WORDLIST_H"

puts "const char * const words[] = {"

File.open(WORDLIST, 'r') do |wl|
  wl.each_line do |line|
    print '"' + line.strip + '"'
    unless wl.eof?
      puts ","
    else
      puts ""
    end
  end
end

puts "};"

puts "#endif"
